### PR TITLE
Add more github action tests

### PR DESCRIPTION
**Pull request by jerry-skydio**
Run checks under multiple python versions
and also check the package build and lint.

Reviewers: greg-b

### CODE REVIEW

**Comment by jerry-skydio** [comment]
Reviews in this chain:
└**https://github.com/Skydio/revup/pull/39** **Add more github action tests**

**Comment by jerry-skydio** [comment]
| # | head | base | diff | date | summary |
| - | - | - | - | - | - |
| 0 | [fe552788](/Skydio/revup/commit/fe552788b028755cb242d49d50d8c44bcf15c229) | [b64cf3b0](/Skydio/revup/commit/b64cf3b04014bad373ab4479215f3824dff7b73f) | [diff](/Skydio/revup/compare/b64cf3b04014bad373ab4479215f3824dff7b73f..fe552788b028755cb242d49d50d8c44bcf15c229) | Sep 14 8:34 PM |  1 file changed, 18 insertions(+), 7 deletions(-) |

**Review by gbalke — APPROVED** [review]
LGTM.

**Review by gbalke — CHANGES_REQUESTED** [review]
I noticed this when trying to add a `make test` to the Makefile. You've version locked by setting `PYTHON ?= /usr/bin/env python3.8` in the makefile. I think 3.8 is system python for the version of ubuntu being used so it's not erroring even though you're using it instead of 3.9/3.10.
image

If you want to fix this, you'll need to either override `PYTHON` with
`PYTHON=python make lint` (I think this should work???) or remove the definition in the makefile (locking it in the makefile seems strange in the first place... I would set it to `PYTHON ?= python3`).

**Comment by jerry-skydio** [comment]
i set it to python3.8 to be guaranteed to work (at least on my computer). python3 for me is 3.6 so i imagine it wouldn't be guaranteed to work for others as well. afaik there's no 100% incantation for py>=3.8 so the PYTHON= is probably the way to go

**Review by greg-balke-skydio — APPROVED** [review]
Might be good to add something that runs `python --version` just for validation purposes.

**Pull request merged**
