### PR TITLE
[Github] Workflow for testing installation

### PR DESCRIPTION
**Pull request by gbalke**
This tests installation of revup with various versions of python.

Signed-off-by: Greg Balke <gbalke@berkeley.edu>

Topic: github_workflow_python_install
Reviewers: jerry-skydio

### CODE REVIEW

**Comment by gbalke** [comment]
Reviews in this chain:
└**https://github.com/Skydio/revup/pull/38** **[Github] Workflow for testing installation**

**Comment by gbalke** [comment]
| # | head | base | diff | date | summary |
| - | - | - | - | - | - |
| 0 | [05aad3c4](/gbalke/revup/commit/05aad3c4763c33a4728e35eb470964d6c1fc6f56) | [c6262ecc](/gbalke/revup/commit/c6262eccd8eacbfdf3764110313290605509c08e) | [diff](/gbalke/revup/compare/c6262eccd8eacbfdf3764110313290605509c08e..05aad3c4763c33a4728e35eb470964d6c1fc6f56) | Sep 14 8:24 PM |  1 file changed, 22 insertions(+) |

**Comment by jerry-skydio** [comment]
I adapted these changes here https://github.com/Skydio/revup/pull/39 to also lint in each python version. 

once we have real tests, we can expand to run tests in each python version too

**Comment by gbalke** [comment]
@jerry-skydio tests: https://github.com/gbalke/revup/pull/2. Just need to resolve #41 as I can't push it up here.

**Pull request closed without merging**
